version: '3.1'
services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 24plus
        ports:
          - 27014:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8083:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: 24plus
        depends_on:
          - mongo
    24plus-server:
        build: .
        restart: always
        ports:
          - 5001:80
        environment:
          MongoDB__Host: mongo
        depends_on:
          - mongo
        volumes:
          - ./mobileapp:/app/mobileapp
          - ./logs:/app/logs
          - ./FileUpload:/app/FileUpload