using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace _24hplusdotnetcore.Common.Constants
{
    public static class StatusMapping
    {
        public const string STATUS_PREFIX = "STATUS_{0}";
        public const string DETAIL_STATUS_PREFIX = "STATUS_{0}_DETAIL_{1}";
        public const string DEFAULT = "DEFAULT";

        /// <summary>
        /// ("{ 'STATUS_"; A2;"', '"; B2;"' },")
        /// </summary>
        public static readonly ReadOnlyDictionary<string, string> MA_STATUS_MESSAGE_MAPPING =
            new ReadOnlyDictionary<string, string>(new Dictionary<string, string>()
            {
                { "DEFAULT", "UNDEFINED" },
                { "STATUS_1", "NEW LEAD" },
                { "STATUS_2", "NOT ALLOCATED" },
                { "STATUS_3", "ALLOCATED TO DC" },
                { "STATUS_4", "INVALID ROUTE" },
                { "STATUS_5", "SCHEDULING" },
                { "STATUS_6", "CONFIRM APPOINTMENT" },
                { "STATUS_7", "FOLLOWING" },
                { "STATUS_8", "CONSIDERING" },
                { "STATUS_9", "SUBMITTED AT RO/SIP" },
                { "STATUS_10", "QDE-DOCUMENT" },
                { "STATUS_11", "QDE-APPLICATION" },
                { "STATUS_12", "FULL" },
                { "STATUS_13", "QDE-CANT PROVIDE DOCUMENTS" },
                { "STATUS_14", "CANCELLED" },
                { "STATUS_15", "IN PROGRESS SALES ADMIN" },
                { "STATUS_16", "FINISH SALES ADMIN" },
                { "STATUS_17", "DEFER SALES ADMIN" },
                { "STATUS_18", "IN PROGRESS DE" },
                { "STATUS_19", "DEFER SGB" },
                { "STATUS_20", "DEFER UND" },
                { "STATUS_21", "FINISH DE" },
                { "STATUS_22", "BDE" },
                { "STATUS_23", "PDOC" },
                { "STATUS_24", "QDE" },
                { "STATUS_25", "DOV" },
                { "STATUS_26", "POR" },
                { "STATUS_27", "POL" },
                { "STATUS_28", "UND" },
                { "STATUS_29", "CBC" },
                { "STATUS_30", "DUR" },
                { "STATUS_31", "FII" },
                { "STATUS_32", "DII" },
                { "STATUS_33", "DISBDTL" },
                { "STATUS_34", "DUP" },
                { "STATUS_35", "SCR" },
                { "STATUS_36", "REJ" },
                { "STATUS_37", "FINISH" },
                { "STATUS_38", "CAN" },
                { "STATUS_39", "SRR" },
            });

        /// <summary>
        /// ("{ 'STATUS_"; B2;"_DETAIL_";A2;"', '"; C2;"' },")
        /// </summary>
        public static readonly ReadOnlyDictionary<string, string> MA_DETAIL_STATUS_MESSAGE_MAPPING =
            new ReadOnlyDictionary<string, string>(new Dictionary<string, string>()
            {
                { "DEFAULT", "UNDEFINED" },
                { "STATUS_1_DETAIL_1", "Hồ sơ khách hàng mới vừa nhận" },
                { "STATUS_2_DETAIL_2", "Hồ sơ chưa được phân bổ" },
                { "STATUS_3_DETAIL_3", "Hồ sơ đã phân bổ cho DC" },
                { "STATUS_4_DETAIL_4", "Sai tuyến ( DC note lại địa điểm nhận hồ sơ)" },
                { "STATUS_5_DETAIL_5", "Thuê bao" },
                { "STATUS_5_DETAIL_6", "Không nghe máy" },
                { "STATUS_5_DETAIL_7", "Khách hàng chưa sắp xếp được lịch hẹn" },
                { "STATUS_5_DETAIL_8", "DC chưa sắp xếp được lịch hẹn" },
                { "STATUS_5_DETAIL_9", "Khách hàng chưa chuẩn bị xong hồ sơ" },
                { "STATUS_5_DETAIL_10", "Lý do khác" },
                { "STATUS_6_DETAIL_11", "Đã đặt lịch hẹn với khách hàng 1 ngày tới" },
                { "STATUS_6_DETAIL_12", "Đã đặt lịch hẹn với khách hàng 2 ngày tới" },
                { "STATUS_6_DETAIL_13", "Đã đặt lịch hẹn với khách hàng 3 ngày tới" },
                { "STATUS_7_DETAIL_14", "DC hẹn gọi lại để chốt lịch sau do hẹn quá 3 ngày" },
                { "STATUS_7_DETAIL_15", "DC theo dõi lý do khác (Nghỉ việc)" },
                { "STATUS_8_DETAIL_16", "Khách hàng đang cân nhắc về khoản vay/ cần tư vấn lại" },
                { "STATUS_9_DETAIL_17", "Khách hàng đã nộp hồ sơ tại RO/SIP" },
                { "STATUS_10_DETAIL_18", "Hồ sơ thiếu CMND" },
                { "STATUS_10_DETAIL_19", "Hồ sơ thiếu Hộ khẩu" },
                { "STATUS_10_DETAIL_20", "Hồ sơ thiếu Chứng từ công việc" },
                { "STATUS_10_DETAIL_21", "Hồ sơ thiếu Chứng từ thu nhập" },
                { "STATUS_10_DETAIL_22", "Hồ sơ thiếu Chứng từ cư trú" },
                { "STATUS_10_DETAIL_23", "Hồ sơ thiếu GP DKKD" },
                { "STATUS_10_DETAIL_24", "Hồ sơ thiếu Chứng từ thuế" },
                { "STATUS_10_DETAIL_25", "Hồ sơ thiếu Hóa đơn điện" },
                { "STATUS_10_DETAIL_26", "Hồ sơ thiếu HD BHNT" },
                { "STATUS_10_DETAIL_27", "Hồ sơ thiếu hóa đơn bảo hiểm NT" },
                { "STATUS_10_DETAIL_28", "Hồ sơ thiếu Chứng từ khác" },
                { "STATUS_11_DETAIL_29", "Không cung cấp được thông tin địa chỉ" },
                { "STATUS_11_DETAIL_30", "Không cung cấp được thông tin công việc" },
                { "STATUS_11_DETAIL_31", "Không cung cấp được thông tin thu nhập" },
                { "STATUS_11_DETAIL_32", "Không cung cấp được thông tin người hôn phối" },
                { "STATUS_11_DETAIL_33", "Không cung cấp được số điện thoại tham chiếu" },
                { "STATUS_11_DETAIL_34", "Không cung cấp được thông tin khác" },
                { "STATUS_12_DETAIL_35", "Hồ sơ đầy đủ Upload send to BPO" },
                { "STATUS_12_DETAIL_36", "DC submit app to SIP/RO" },
                { "STATUS_13_DETAIL_37", "Khách hàng không cung cấp được CMND" },
                { "STATUS_13_DETAIL_38", "Khách hàng không cung cấp được Hộ khẩu" },
                { "STATUS_13_DETAIL_39", "Khách hàng không cung cấp được Chứng từ công việc" },
                { "STATUS_13_DETAIL_40", "Khách hàng không cung cấp được Chứng từ thu nhập" },
                { "STATUS_13_DETAIL_41", "Khách hàng không cung cấp được Chứng từ cư trú" },
                { "STATUS_13_DETAIL_42", "Khách hàng không cung cấp được GP DKKD" },
                { "STATUS_13_DETAIL_43", "Khách hàng không cung cấp được Chứng từ thuế" },
                { "STATUS_13_DETAIL_44", "Khách hàng không cung cấp được Hóa đơn Điện" },
                { "STATUS_13_DETAIL_45", "Khách hàng không cung cấp được HD BHNT" },
                { "STATUS_13_DETAIL_46", "Khách hàng không cung cấp được Hóa đơn bảo hiểm NT" },
                { "STATUS_13_DETAIL_47", "Khách hàng không cung cấp được Chứng từ khác" },
                { "STATUS_14_DETAIL_48", "Khách hàng hủy không vay nữa (sau khi Sale đã thuyết phục)" },
                { "STATUS_14_DETAIL_49", "Lead quá thời hạn xử lý (30 ngày)" },
                { "STATUS_14_DETAIL_50", "Lý do khác" },
                { "STATUS_15_DETAIL_51", "Hồ sơ đã chuyển Sales Admin và đang trong quá trình xử lý" },
                { "STATUS_16_DETAIL_52", "Sales Admin hoàn thành xử lý" },
                { "STATUS_18_DETAIL_53", "Hồ sơ đã chuyển sang SGB nhập liệu và đang trong quá trình xử lý" },
                { "STATUS_19_DETAIL_54", "Hồ sơ bị trả về từ SGB (chưa lên AppID)" },
                { "STATUS_20_DETAIL_55", "Hồ sơ bị trả về từ UND (đã lên AppID)" },
                { "STATUS_21_DETAIL_56", "Hồ sơ đã hoàn thành nhập liệu bởi SGB (bao gồm hoàn thành xử lý hồ sơ mới và hồ sơ Defer)" },
                { "STATUS_22_DETAIL_57", "F1 status" },
                { "STATUS_23_DETAIL_58", "F1 status" },
                { "STATUS_24_DETAIL_59", "F1 status" },
                { "STATUS_25_DETAIL_60", "F1 status" },
                { "STATUS_26_DETAIL_61", "F1 status" },
                { "STATUS_27_DETAIL_62", "F1 status" },
                { "STATUS_28_DETAIL_63", "F1 status" },
                { "STATUS_29_DETAIL_64", "F1 status" },
                { "STATUS_30_DETAIL_65", "F1 status" },
                { "STATUS_31_DETAIL_66", "F1 status" },
                { "STATUS_32_DETAIL_67", "F1 status" },
                { "STATUS_33_DETAIL_68", "F1 status" },
                { "STATUS_34_DETAIL_69", "F1 status" },
                { "STATUS_35_DETAIL_70", "F1 status" },
                { "STATUS_36_DETAIL_71", "F1 status" },
                { "STATUS_37_DETAIL_72", "F1 status" },
                { "STATUS_38_DETAIL_73", "F1 status" },
                { "STATUS_39_DETAIL_74", "F1 status" },
                { "STATUS_17_DETAIL_75", "1.1 - Mờ không rõ thông tin" },
                { "STATUS_17_DETAIL_76", "1.2 - App thiếu/sai thông tin khách hàng vay" },
                { "STATUS_17_DETAIL_77", "1.3 - App thiếu/sai thông tin cư trú và thời gian cư trú" },
                { "STATUS_17_DETAIL_78", "1.4 - App thiếu/sai thông tin khoản vay" },
                { "STATUS_17_DETAIL_79", "1.5 - App thiếu/sai thông tin nghề nghiệp" },
                { "STATUS_17_DETAIL_80", "1.6 - App thiếu/sai thông tin thu nhập" },
                { "STATUS_17_DETAIL_81", "1.7 - App thiếu/sai thông tin vợ/chồng" },
                { "STATUS_17_DETAIL_82", "1.8 - App thiếu/sai thông tin, rule tham chiếu" },
                { "STATUS_17_DETAIL_83", "1.9 - App thiếu chữ ký khách hàng" },
                { "STATUS_17_DETAIL_84", "1.10 - Thiếu/sai code sale, code nhân viên tư vấn" },
                { "STATUS_17_DETAIL_85", "2.1 - CMND/Thẻ CCCD mờ do chất lượng ảnh Sales chụp" },
                { "STATUS_17_DETAIL_86", "2.2 - CMND/Thẻ CCCD mờ do bản thân CMND bị mờ" },
                { "STATUS_17_DETAIL_87", "2.3 - CMND/Thẻ CCCD hết hạn" },
                { "STATUS_17_DETAIL_88", "2.4 - Không cung cấp CMND cũ/chứng từ liên quan khi nộp CCCD mới" },
                { "STATUS_17_DETAIL_89", "2.5 - Không trùng khớp trên các giấy tờ khác nhau" },
                { "STATUS_17_DETAIL_90", "2.6 - Scan thiếu/mất góc" },
                { "STATUS_17_DETAIL_91", "3.1 - Hộ khẩu mờ do chất lượng ảnh Sales chụp" },
                { "STATUS_17_DETAIL_92", "3.2 - Hộ khẩu công chứng hết hạn (6 tháng)" },
                { "STATUS_17_DETAIL_93", "3.3 - Hộ khẩu thiếu trang/không hợp lệ" },
                { "STATUS_17_DETAIL_94", "3.4 - Khác" },
                { "STATUS_17_DETAIL_95", "4.1 - Thiếu KT3/XN tạm trú/Thông báo tạm trú/Thẻ tạm trú" },
                { "STATUS_17_DETAIL_96", "4.2 - KT3/XN tạm trú/TB tạm trú mờ do chất lượng ảnh Sales chụp" },
                { "STATUS_17_DETAIL_97", "4.3 - KT3 công chứng hết hạn (6 tháng)" },
                { "STATUS_17_DETAIL_98", "4.4 - KT3 thiếu trang" },
                { "STATUS_17_DETAIL_99", "4.5 - KT3/XN tạm trú hết hạn" },
                { "STATUS_17_DETAIL_100", "5.1 - Thiếu BHYT" },
                { "STATUS_17_DETAIL_101", "5.2 - Mã không hợp lệ" },
                { "STATUS_17_DETAIL_102", "5.3 - BHYT Mờ" },
                { "STATUS_17_DETAIL_103", "5.4 - BHYT Hết hạn" },
                { "STATUS_17_DETAIL_104", "6.1 - Thiếu Hợp đồng lao động/Phụ lục hợp đồng/Xác nhận công tác" },
                { "STATUS_17_DETAIL_105", "6.2 - Hợp đồng lao động/Phụ lục hợp đồng/Xác nhận công tác mờ do chất lượng Sales chụp" },
                { "STATUS_17_DETAIL_106", "6.3 - Hợp đồng lao động/Xác nhận công tác hết hạn" },
                { "STATUS_17_DETAIL_107", "6.4 - Khác" },
                { "STATUS_17_DETAIL_108", "7.1 - Sao kê lương/Phiếu lương/Xác nhận lương mờ do Sales chụp" },
                { "STATUS_17_DETAIL_109", "7.2 - Sao kê lương/Phiếu lương/Xác nhận lương không đủ 3 tháng lương gần nhất" },
                { "STATUS_17_DETAIL_110", "7.3 - Sao kê lương/Phiếu lương/Xác nhận lương không có mộc ngân hàng/công ty" },
                { "STATUS_17_DETAIL_111", "7.4 - Khác" },
                { "STATUS_17_DETAIL_112", "8.1 - Giấy phép ĐKKD mờ do chất lượng ảnh Sales chụp" },
                { "STATUS_17_DETAIL_113", "8.2 - Giấy phép ĐKKD chưa đủ 6 tháng" },
                { "STATUS_17_DETAIL_114", "9.1 - Thiếu Hóa đơn/Biên nhận dịch vụ hoặc Thông báo có dấu \"Đã thu tiền\"" },
                { "STATUS_17_DETAIL_115", "9.2 - Hóa đơn mờ do chất lượng ảnh Sales chụp" },
                { "STATUS_17_DETAIL_116", "9.3 - Hóa đơn hết hạn (3 tháng)" },
                { "STATUS_17_DETAIL_117", "9.4 - Khách nộp thông báo tiền điện KHÔNG có mộc \"Đã thu tiền\"" },
                { "STATUS_17_DETAIL_118", "9.5 – Khác" },
                { "STATUS_17_DETAIL_119", "10.1 - Thiếu Hợp đồng/Lịch thanh toán,Hóa đơn/ Biên nhận thanh toán khoản vay hiện tại" },
                { "STATUS_17_DETAIL_120", "10.2 - Hợp đồng/Lịch thanh toán,Hóa đơn/ Biên nhận thanh toán khoản vay hiện tại không hợp lệ" },
                { "STATUS_17_DETAIL_121", "11.1 - Không view được file" },
                { "STATUS_17_DETAIL_122", "11.2 - Hồ sơ thiếu file DN" },
                { "STATUS_17_DETAIL_123", "11.3 - Đặt sai cấu trúc folder" },
                { "STATUS_17_DETAIL_124", "11.4 - Up trùng hồ sơ" },
                { "STATUS_17_DETAIL_125", "12.1 - Sai từ 2 code trở lên" },
                { "STATUS_17_DETAIL_126", "12.2 - Khác" },
                { "STATUS_14_DETAIL_127", "Quá số lần defer" },
                { "STATUS_14_DETAIL_128", "Quá số lần defer - Sales Admin" },
                { "STATUS_14_DETAIL_129", "Quá số lần defer - SGB" },
                { "STATUS_14_DETAIL_130", "Hết hạn bổ sung defer Sales Admin" },
                { "STATUS_14_DETAIL_131", "Hết hạn bổ sung defer SGB" },
                { "STATUS_14_DETAIL_132", "Hết hạn bổ sung defer UND" }
            });

        /// <summary>
        /// ("{ 'STATUS_"; A2;"', '"; E2;"' },")
        /// </summary>
        public static readonly ReadOnlyDictionary<string, string> CRM_STATUS_MESSAGE_MAPPING =
            new ReadOnlyDictionary<string, string>(new Dictionary<string, string>() {
                { "DEFAULT", "UNDEFINED" },
                { "STATUS_1", "Trong quá trình thẩm định" },
                { "STATUS_2", "Trong quá trình thẩm định" },
                { "STATUS_3", "Trong quá trình thẩm định" },
                { "STATUS_4", "Trong quá trình thẩm định" },
                { "STATUS_5", "Trong quá trình thẩm định" },
                { "STATUS_6", "Trong quá trình thẩm định" },
                { "STATUS_7", "Trong quá trình thẩm định" },
                { "STATUS_8", "Trong quá trình thẩm định" },
                { "STATUS_9", "Trong quá trình thẩm định" },
                { "STATUS_10", "Trong quá trình thẩm định" },
                { "STATUS_11", "Trong quá trình thẩm định" },
                { "STATUS_12", "Trong quá trình thẩm định" },
                { "STATUS_13", "Trong quá trình thẩm định" },
                { "STATUS_14", "Hồ sơ bị hủy / từ chối" },
                { "STATUS_15", "Trong quá trình thẩm định" },
                { "STATUS_16", "Trong quá trình thẩm định" },
                { "STATUS_17", "Trong quá trình thẩm định" },
                { "STATUS_18", "Trong quá trình thẩm định" },
                { "STATUS_19", "Trong quá trình thẩm định" },
                { "STATUS_20", "Trong quá trình thẩm định" },
                { "STATUS_21", "Trong quá trình thẩm định" },
                { "STATUS_22", "Trong quá trình thẩm định" },
                { "STATUS_23", "Trong quá trình thẩm định" },
                { "STATUS_24", "Trong quá trình thẩm định" },
                { "STATUS_25", "Trong quá trình thẩm định" },
                { "STATUS_26", "Trong quá trình thẩm định" },
                { "STATUS_27", "Trong quá trình thẩm định" },
                { "STATUS_28", "Trong quá trình thẩm định" },
                { "STATUS_29", "Trong quá trình thẩm định" },
                { "STATUS_30", "Trong quá trình thẩm định" },
                { "STATUS_31", "Trong quá trình thẩm định" },
                { "STATUS_32", "Trong quá trình thẩm định" },
                { "STATUS_33", "Trong quá trình thẩm định" },
                { "STATUS_34", "Trong quá trình thẩm định" },
                { "STATUS_35", "Trong quá trình thẩm định" },
                { "STATUS_36", "Hồ sơ bị hủy / từ chối" },
                { "STATUS_37", "Giải ngân thành công" },
                { "STATUS_38", "Trong quá trình thẩm định" },
                { "STATUS_39", "Trong quá trình thẩm định" },
            });
    }
}
